### ISSUE TITLE
Evaluation of Catch2

### ISSUE THREAD

**Issue by hobovsky** [codewars/next-cpp#1]
I managed to install Catch2 locally (the amalgamated version) and run the example test suite. I will use this post as an area to dump potentially interesting facts I managed to figure out, but maybe it would be worth to enable discussions in this repository?

--------

### Organization of tests

I think I figured out why you could not get the reporter to behave nicely. It turns out that Catch2 uses quite peculiar way of organization of tests: it does not follow the CW's-favorite `describe`/`it`/`assert` way of organization. Instead, it seems to resemble Julia's FactCheck, where Catch2's `TEST_CASE` is FactCheck's `@facts`, `SECTION` seems to correspond to `@context`, and `REQUIRE` is a `@fact`. As a result, it can be difficult to make a reporter which handles the organization artifacts with `<DESCRIBE::>` and `<IT::>`, because we will encounter similar problems as with Julia's setup, where we do not know what is an outer level, and what is the innermost level. Catch2's BDD mode does not seem to be helpful here either, because the `GIVEN/WHEN/THEN` just map to `SECTION` and we still do not know when we are in the innermost one. It _could_ work if we forced some CW-specific convention, but I think it's not something what we want. Or, if the reporter can keep/pass state between events, it can try to deduce if it needs to emit an `<IT::>` at the point it attempts to emit `<PASSED::>` or `<FAILED::>`. I can give it a shot, but this this also feels a bit off (related: https://github.com/codewars/runner/issues/262).

**Comment by kazk** [comment]
> maybe it would be worth to enable discussions in this repository?

I don't know, but enabled it :)

**Comment by hobovsky** [comment]
I moved the info to this discussion: https://github.com/codewars/next-cpp/discussions/2 where I hope it will be easier to discuss various aspects in threads.
